/**
 * Type definitions for the Community Calculation Database.
 *
 * Schema follows conventions from Materials Project, NOMAD, and AFLOW:
 *   - Structure metadata (formula, elements, atom count, lattice)
 *   - Calculation parameters (model, type, software version)
 *   - Computed results (energy, forces, volume)
 *   - Contributor metadata (optional institution, notes)
 *
 * SCOPE: Currently records calculations from the General Calculator
 * (/calculate) only. Semiconductor page integration is planned for a
 * future release — see TODO in /api/community/share/route.ts.
 */

// ---------------------------------------------------------------------------
// Database row — matches the Supabase `calculations` table exactly
// ---------------------------------------------------------------------------

export interface CommunityCalculation {
  /** UUID primary key (auto-generated by Supabase) */
  id: string;

  /** ISO timestamp (auto-generated by Supabase) */
  created_at: string;

  // ── Structure metadata ──────────────────────────────────────────────────

  /** Chemical formula, e.g. "C2H6O", "Si8", "GaAs" */
  formula: string;

  /** Sorted unique element list, e.g. ["C","H","O"] */
  elements: string[];

  /** Total number of atoms in the structure */
  atom_count: number;

  /** Original filename uploaded by user */
  filename: string;

  /** File format: "xyz", "cif", "poscar", "pdb" */
  file_format: string;

  // ── Calculation parameters ──────────────────────────────────────────────

  /** MACE model type: "MACE-MP-0" or "MACE-OFF" */
  model_type: string;

  /** MACE model size: "small", "medium", "large" */
  model_size: string;

  /** Calculation type: "single-point", "geometry-opt", "molecular-dynamics" */
  calc_type: string;

  /** Whether dispersion correction was enabled */
  dispersion: boolean;

  // ── Computed results ────────────────────────────────────────────────────

  /** Total energy in eV (null if calculation failed) */
  energy_ev: number | null;

  /** Energy per atom in eV (null if N/A) */
  energy_per_atom_ev: number | null;

  /** RMS force magnitude in eV/Å (null if N/A) */
  rms_force_ev_a: number | null;

  /** Max force magnitude in eV/Å (null if N/A) */
  max_force_ev_a: number | null;

  /** Cell volume in ų (null if non-periodic) */
  volume_a3: number | null;

  /** Calculation wall time in seconds (null if not recorded) */
  calc_time_s: number | null;

  // ── MD-specific (optional) ──────────────────────────────────────────────

  /** Number of MD steps (null if not MD) */
  md_steps: number | null;

  /** MD ensemble: "NVE", "NVT", "NPT" (null if not MD) */
  md_ensemble: string | null;

  /** MD temperature in Kelvin (null if not MD) */
  md_temperature_k: number | null;

  // ── Contributor metadata ────────────────────────────────────────────────

  /** Contributor display name (default: "Anonymous") */
  contributor: string;

  /** Institution / affiliation (optional) */
  institution: string | null;

  /** Free-text notes from the contributor (optional) */
  notes: string | null;

  /** Whether this record is publicly visible */
  is_public: boolean;
}

// ---------------------------------------------------------------------------
// Insert payload — omits auto-generated fields
// ---------------------------------------------------------------------------

export type CommunityCalculationInsert = Omit<
  CommunityCalculation,
  "id" | "created_at"
>;

// ---------------------------------------------------------------------------
// Filters for the community browsing page
// ---------------------------------------------------------------------------

export interface CommunityFilters {
  /** Filter by formula (partial match) */
  formula?: string;

  /** Filter by calculation type */
  calcType?: string;

  /** Filter by model type */
  modelType?: string;

  /** Filter by institution (partial match) */
  institution?: string;

  /** Sort field */
  sortBy?: "created_at" | "energy_ev" | "atom_count" | "formula";

  /** Sort direction */
  sortDir?: "asc" | "desc";
}
